# 应用服务 WEB 访问端口
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhanhong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
tbserver:
  ip: 192.168.200.128:9090
  start-url: /api/plugins/telemetry/DEVICE/
  end-url: /values/timeseries
  #tb租户管理员账号密码
  username: tenant@thingsboard.org
  password: tenant